# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5dbc1643-a2ff-4d0e-ad11-06c4d6be2adb";
    fsType = "btrfs";
    options = ["subvol=root" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/5dbc1643-a2ff-4d0e-ad11-06c4d6be2adb";
    fsType = "btrfs";
    options = ["subvol=home" "noatime" "compress=zstd"];
  };

  fileSystems."/var/lib" = {
    device = "/dev/disk/by-uuid/5dbc1643-a2ff-4d0e-ad11-06c4d6be2adb";
    fsType = "btrfs";
    options = ["subvol=var-lib" "noatime"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/5dbc1643-a2ff-4d0e-ad11-06c4d6be2adb";
    fsType = "btrfs";
    options = ["subvol=persist" "noatime"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/5dbc1643-a2ff-4d0e-ad11-06c4d6be2adb";
    fsType = "btrfs";
    options = ["subvol=var-log" "noatime" "compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1D88-CA78";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/5dbc1643-a2ff-4d0e-ad11-06c4d6be2adb";
    fsType = "btrfs";
    options = ["subvol=nix" "noatime" "compress=zstd"];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/9df405de-2d30-4c94-9058-703091da9f73";
    fsType = "btrfs";
    options = ["noatime"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  systemd.services.wakeonlan = {
    description = "Reenable Wake-on-LAN every boot";
    after = ["network.target"];
    serviceConfig = {
      Type = "simple";
      RemainAfterExit = true;
      ExecStart = "${pkgs.ethtool}/sbin/ethtool -s enp5s0 wol g";
    };
    wantedBy = ["default.target"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
